export default {
  BELGIUM: 'BE',
  CANADA: 'CA',
  FRANCE: 'FR',
  GERMANY: 'DE',
  ITALY: 'IT',
  LUXEMBOURG: 'LU',
  MALAYSIA: 'MY',
  PORTUGAL: 'PT',
  SPAIN: 'ES',
  SWITZERLAND: 'CH',
  UNITED_KINGDOM: 'GB',
  UNITED_STATES: 'US',
};
