// flow-typed signature: a81bdf9b2fd2d05040be9eddcd71aec0
// flow-typed version: <<STUB>>/jsonlint_v^1.6.3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonlint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonlint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonlint/lib/cli' {
  declare module.exports: any;
}

declare module 'jsonlint/lib/formatter' {
  declare module.exports: any;
}

declare module 'jsonlint/lib/jsonlint' {
  declare module.exports: any;
}

declare module 'jsonlint/scripts/bundle' {
  declare module.exports: any;
}

declare module 'jsonlint/test/all-tests' {
  declare module.exports: any;
}

declare module 'jsonlint/web/json2' {
  declare module.exports: any;
}

declare module 'jsonlint/web/jsonlint' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonlint/lib/cli.js' {
  declare module.exports: $Exports<'jsonlint/lib/cli'>;
}
declare module 'jsonlint/lib/formatter.js' {
  declare module.exports: $Exports<'jsonlint/lib/formatter'>;
}
declare module 'jsonlint/lib/jsonlint.js' {
  declare module.exports: $Exports<'jsonlint/lib/jsonlint'>;
}
declare module 'jsonlint/scripts/bundle.js' {
  declare module.exports: $Exports<'jsonlint/scripts/bundle'>;
}
declare module 'jsonlint/test/all-tests.js' {
  declare module.exports: $Exports<'jsonlint/test/all-tests'>;
}
declare module 'jsonlint/web/json2.js' {
  declare module.exports: $Exports<'jsonlint/web/json2'>;
}
declare module 'jsonlint/web/jsonlint.js' {
  declare module.exports: $Exports<'jsonlint/web/jsonlint'>;
}
