// flow-typed signature: 1c95bcdf9027f05efe521552d541004f
// flow-typed version: <<STUB>>/sip.js_v^0.11.3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sip.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sip.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sip.js/dist/sip-0.11.3' {
  declare module.exports: any;
}

declare module 'sip.js/dist/sip-0.11.3.min' {
  declare module.exports: any;
}

declare module 'sip.js/dist/sip' {
  declare module.exports: any;
}

declare module 'sip.js/dist/sip.min' {
  declare module.exports: any;
}

declare module 'sip.js/karma.conf' {
  declare module.exports: any;
}

declare module 'sip.js/src/ClientContext' {
  declare module.exports: any;
}

declare module 'sip.js/src/Constants' {
  declare module.exports: any;
}

declare module 'sip.js/src/Dialog/RequestSender' {
  declare module.exports: any;
}

declare module 'sip.js/src/Dialogs' {
  declare module.exports: any;
}

declare module 'sip.js/src/DigestAuthentication' {
  declare module.exports: any;
}

declare module 'sip.js/src/environment_browser' {
  declare module.exports: any;
}

declare module 'sip.js/src/environment' {
  declare module.exports: any;
}

declare module 'sip.js/src/EventEmitter' {
  declare module.exports: any;
}

declare module 'sip.js/src/Exceptions' {
  declare module.exports: any;
}

declare module 'sip.js/src/Grammar' {
  declare module.exports: any;
}

declare module 'sip.js/src/index' {
  declare module.exports: any;
}

declare module 'sip.js/src/LoggerFactory' {
  declare module.exports: any;
}

declare module 'sip.js/src/NameAddrHeader' {
  declare module.exports: any;
}

declare module 'sip.js/src/Parser' {
  declare module.exports: any;
}

declare module 'sip.js/src/PublishContext' {
  declare module.exports: any;
}

declare module 'sip.js/src/RegisterContext' {
  declare module.exports: any;
}

declare module 'sip.js/src/RequestSender' {
  declare module.exports: any;
}

declare module 'sip.js/src/SanityCheck' {
  declare module.exports: any;
}

declare module 'sip.js/src/ServerContext' {
  declare module.exports: any;
}

declare module 'sip.js/src/Session' {
  declare module.exports: any;
}

declare module 'sip.js/src/Session/DTMF' {
  declare module.exports: any;
}

declare module 'sip.js/src/SessionDescriptionHandler' {
  declare module.exports: any;
}

declare module 'sip.js/src/SIP' {
  declare module.exports: any;
}

declare module 'sip.js/src/SIPMessage' {
  declare module.exports: any;
}

declare module 'sip.js/src/Subscription' {
  declare module.exports: any;
}

declare module 'sip.js/src/Timers' {
  declare module.exports: any;
}

declare module 'sip.js/src/Transactions' {
  declare module.exports: any;
}

declare module 'sip.js/src/Transport' {
  declare module.exports: any;
}

declare module 'sip.js/src/UA' {
  declare module.exports: any;
}

declare module 'sip.js/src/URI' {
  declare module.exports: any;
}

declare module 'sip.js/src/Utils' {
  declare module.exports: any;
}

declare module 'sip.js/src/Web/Modifiers' {
  declare module.exports: any;
}

declare module 'sip.js/src/Web/SessionDescriptionHandler' {
  declare module.exports: any;
}

declare module 'sip.js/src/Web/SessionDescriptionHandlerObserver' {
  declare module.exports: any;
}

declare module 'sip.js/src/Web/Simple' {
  declare module.exports: any;
}

declare module 'sip.js/src/Web/Transport' {
  declare module.exports: any;
}

declare module 'sip.js/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sip.js/dist/sip-0.11.3.js' {
  declare module.exports: $Exports<'sip.js/dist/sip-0.11.3'>;
}
declare module 'sip.js/dist/sip-0.11.3.min.js' {
  declare module.exports: $Exports<'sip.js/dist/sip-0.11.3.min'>;
}
declare module 'sip.js/dist/sip.js' {
  declare module.exports: $Exports<'sip.js/dist/sip'>;
}
declare module 'sip.js/dist/sip.min.js' {
  declare module.exports: $Exports<'sip.js/dist/sip.min'>;
}
declare module 'sip.js/karma.conf.js' {
  declare module.exports: $Exports<'sip.js/karma.conf'>;
}
declare module 'sip.js/src/ClientContext.js' {
  declare module.exports: $Exports<'sip.js/src/ClientContext'>;
}
declare module 'sip.js/src/Constants.js' {
  declare module.exports: $Exports<'sip.js/src/Constants'>;
}
declare module 'sip.js/src/Dialog/RequestSender.js' {
  declare module.exports: $Exports<'sip.js/src/Dialog/RequestSender'>;
}
declare module 'sip.js/src/Dialogs.js' {
  declare module.exports: $Exports<'sip.js/src/Dialogs'>;
}
declare module 'sip.js/src/DigestAuthentication.js' {
  declare module.exports: $Exports<'sip.js/src/DigestAuthentication'>;
}
declare module 'sip.js/src/environment_browser.js' {
  declare module.exports: $Exports<'sip.js/src/environment_browser'>;
}
declare module 'sip.js/src/environment.js' {
  declare module.exports: $Exports<'sip.js/src/environment'>;
}
declare module 'sip.js/src/EventEmitter.js' {
  declare module.exports: $Exports<'sip.js/src/EventEmitter'>;
}
declare module 'sip.js/src/Exceptions.js' {
  declare module.exports: $Exports<'sip.js/src/Exceptions'>;
}
declare module 'sip.js/src/Grammar.js' {
  declare module.exports: $Exports<'sip.js/src/Grammar'>;
}
declare module 'sip.js/src/index.js' {
  declare module.exports: $Exports<'sip.js/src/index'>;
}
declare module 'sip.js/src/LoggerFactory.js' {
  declare module.exports: $Exports<'sip.js/src/LoggerFactory'>;
}
declare module 'sip.js/src/NameAddrHeader.js' {
  declare module.exports: $Exports<'sip.js/src/NameAddrHeader'>;
}
declare module 'sip.js/src/Parser.js' {
  declare module.exports: $Exports<'sip.js/src/Parser'>;
}
declare module 'sip.js/src/PublishContext.js' {
  declare module.exports: $Exports<'sip.js/src/PublishContext'>;
}
declare module 'sip.js/src/RegisterContext.js' {
  declare module.exports: $Exports<'sip.js/src/RegisterContext'>;
}
declare module 'sip.js/src/RequestSender.js' {
  declare module.exports: $Exports<'sip.js/src/RequestSender'>;
}
declare module 'sip.js/src/SanityCheck.js' {
  declare module.exports: $Exports<'sip.js/src/SanityCheck'>;
}
declare module 'sip.js/src/ServerContext.js' {
  declare module.exports: $Exports<'sip.js/src/ServerContext'>;
}
declare module 'sip.js/src/Session.js' {
  declare module.exports: $Exports<'sip.js/src/Session'>;
}
declare module 'sip.js/src/Session/DTMF.js' {
  declare module.exports: $Exports<'sip.js/src/Session/DTMF'>;
}
declare module 'sip.js/src/SessionDescriptionHandler.js' {
  declare module.exports: $Exports<'sip.js/src/SessionDescriptionHandler'>;
}
declare module 'sip.js/src/SIP.js' {
  declare module.exports: $Exports<'sip.js/src/SIP'>;
}
declare module 'sip.js/src/SIPMessage.js' {
  declare module.exports: $Exports<'sip.js/src/SIPMessage'>;
}
declare module 'sip.js/src/Subscription.js' {
  declare module.exports: $Exports<'sip.js/src/Subscription'>;
}
declare module 'sip.js/src/Timers.js' {
  declare module.exports: $Exports<'sip.js/src/Timers'>;
}
declare module 'sip.js/src/Transactions.js' {
  declare module.exports: $Exports<'sip.js/src/Transactions'>;
}
declare module 'sip.js/src/Transport.js' {
  declare module.exports: $Exports<'sip.js/src/Transport'>;
}
declare module 'sip.js/src/UA.js' {
  declare module.exports: $Exports<'sip.js/src/UA'>;
}
declare module 'sip.js/src/URI.js' {
  declare module.exports: $Exports<'sip.js/src/URI'>;
}
declare module 'sip.js/src/Utils.js' {
  declare module.exports: $Exports<'sip.js/src/Utils'>;
}
declare module 'sip.js/src/Web/Modifiers.js' {
  declare module.exports: $Exports<'sip.js/src/Web/Modifiers'>;
}
declare module 'sip.js/src/Web/SessionDescriptionHandler.js' {
  declare module.exports: $Exports<'sip.js/src/Web/SessionDescriptionHandler'>;
}
declare module 'sip.js/src/Web/SessionDescriptionHandlerObserver.js' {
  declare module.exports: $Exports<'sip.js/src/Web/SessionDescriptionHandlerObserver'>;
}
declare module 'sip.js/src/Web/Simple.js' {
  declare module.exports: $Exports<'sip.js/src/Web/Simple'>;
}
declare module 'sip.js/src/Web/Transport.js' {
  declare module.exports: $Exports<'sip.js/src/Web/Transport'>;
}
declare module 'sip.js/webpack.config.js' {
  declare module.exports: $Exports<'sip.js/webpack.config'>;
}
